// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using prj_core_api.Data;

namespace prj_core_api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200521151311_versao01")]
    partial class versao01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("prj_core_api.Models.Aluno", b =>
                {
                    b.Property<int>("AlunoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DtNascimento");

                    b.Property<string>("Nome");

                    b.Property<int>("ProfessorId");

                    b.Property<string>("Sobrenome");

                    b.HasKey("AlunoId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            AlunoId = 1,
                            DtNascimento = "01/01/2000",
                            Nome = "Daniel",
                            ProfessorId = 1,
                            Sobrenome = "Silva"
                        },
                        new
                        {
                            AlunoId = 2,
                            DtNascimento = "01/01/2000",
                            Nome = "João",
                            ProfessorId = 2,
                            Sobrenome = "Queiroz"
                        },
                        new
                        {
                            AlunoId = 3,
                            DtNascimento = "01/01/2000",
                            Nome = "Hanna",
                            ProfessorId = 3,
                            Sobrenome = "Silva"
                        });
                });

            modelBuilder.Entity("prj_core_api.Models.Professor", b =>
                {
                    b.Property<int>("ProfessorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("ProfessorId");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            ProfessorId = 1,
                            Nome = "Claudio"
                        },
                        new
                        {
                            ProfessorId = 2,
                            Nome = "Silvana"
                        },
                        new
                        {
                            ProfessorId = 3,
                            Nome = "Hanna"
                        });
                });

            modelBuilder.Entity("prj_core_api.Models.Aluno", b =>
                {
                    b.HasOne("prj_core_api.Models.Professor", "Professor")
                        .WithMany("Alunos")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
